### ISSUE TITLE
Mot de passe

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#146]
Sur la version 4.0.2, je ne parviens pas à changer le mot de passe de la plateforme administrateur. Lorsque je sauvegarde, le message d'erreur "COMMON.NOTIFICATION.ERROR.28410 apparaît.
Auriez-vous une solution ? (LinShare 4.0.2 sur Debian 10)

**Comment by marwanJebahi** [comment]
Hello,
Thank you for your feedback.
We have an issue in progress concerning this bug, it will be treated ASAP.
If the entered password does not satisfy the conditions set  in your `linshare.properties` of the password conplexity, you will receive 400 bad request with an error `28410`, you can check this section:
```
# Minimum length of password
password.min.length=12

# Maximum length of password
password.max.length=30

# Minimum Number of uppercase in password
uppercase.character.password=1

# Minimum Number of lowercase in password
lowercase.character.password=1

# Minimum Number of digits in password
digits.character.password=1

# Minimum Number of special characters in password
special.character.password=1
```

Here is the error message which you will receive:

```
[Password must be 12 or more characters in length., Password must contain 1 or more uppercase characters., Password must contain 1 or more digit characters., Password must contain 1 or more special characters.]
```

Regards.

**Comment by EPTBSGL** [comment]
J'ai vérifié cette section et toutes les lignes sont commentées.  Donc, ça ne vient pas de là...

**Comment by marwanJebahi** [comment]
Can you send me the Tomcat log traces please?

**Comment by EPTBSGL** [comment]
Bonjour,
Je viens de regarder catalina.out et effectivement, c'est bien un problème de politique de mot de passe. Donc quand toutes les lignes sont commentées, la politique de mot de passe s'applique quand même. Comment faire pour supprimer cette politique de mot de passe ? Comment faire pour qu'il n'y ait pas besoin de caractères spéciaux ? (si je mets special.character.password=0, la fenêtre de connexion ne s'affiche plus).

**Comment by Barsounal** [comment]
Hello,

The password complexity validator is integrated on LinShare, so every new password will be checked aims to enhance the security's level, When you comment the different keys of defining the password's complexity rules it won't disable the password check, because theses values are used to know the number of min and max of different criteria, and when you will put for example  `password.min.length=0` you will get an error when starting the server `argument must be greater than zero`, which is an error from the framework which is validating these rules.

Regards.

**Comment by EPTBSGL** [comment]
Ok. Merci pour votre réponse.
