### ISSUE TITLE
The request was rejected because the URL contained a potentially malicious String ";"

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#159]
HI,
I'm getting below Error When I run the user interface "http://linshare-user.local/linshare" on browser. There is no issue for accessing administration interface. Can you help me to resolve it.

Linshare version : linshare-ui-user-4.1.0
Product version : 4.1.0

O/S : Red Hat Enterprise Linux release 8.3 

======http://linshare-user.local/linshare/;jsessionid=87F97D4DF98249B7A54E9D59076F4803==========
HTTP Status 500 – Internal Server Error
Type Exception Report

Message The request was rejected because the URL contained a potentially malicious String ";"

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
	org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:456)
	org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:429)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:196)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.43
==================================
Thanks,
JInju

**Comment by fmartin-linagora** [comment]
Hi,

To prevent tomcat to use cookie in the URL with the ";" character, you should disable this behaviour:
`sed -i -e '/<session-config>/ a\        <tracking-mode>COOKIE</tracking-mode>' /usr/local/tomcat/conf/web.xml`
You obvioulsy use the proper path for this config file according to your installation.

In order to access to the user interface, you should try to access to "http://linshare-user.local/" instead of http://linshare-user.local/linshare" which is the landing page of the backend (no other interface there at all.)

Regards,
Fred.

**Comment by annmaria1** [comment]
Hi Fred,

It's resolved without any change.

[image: image.png]

Thanks
Jinju
