### ISSUE TITLE
guest sharedspace quota

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#180]
Hi,
on my configuration, I have 40GB for sharedspace of the domain with the same value for subdomains but the guest sharedspace quota is different by default (20GB).
Shouldn't it be the same value?
Are they different sharedspaces between domain users and guests one?
some screenshots:
![image](https://user-images.githubusercontent.com/33221710/130057373-7f29cb3b-3f1e-4bef-86d3-9707a2779329.png)

![image](https://user-images.githubusercontent.com/33221710/130057502-16e16b0c-ae7e-4a32-b39e-2cc0ee41397d.png)

Kind regards,

**Comment by fmartin-linagora** [comment]
Hi,
I'm not sure I'm getting your issue. 

For each domain, you have a quota for it and two containers, one for personal spaces and one for workgroups. All users belong to a domain. For Guests, it is a bit specific because they are created into their own domain. So they have their own quota and containers.

NB: When a wg is created, it is linked with the container "workgroup" of the author of the wokrgroup.

**Comment by matdemb** [comment]
I thought that the workspace was the same for all users.
So that's normal I have 2 differents parameters as it's 2 differents container, one for the domain and the other for guests.
Thanks for the explanation.

**Comment by fmartin-linagora** [comment]
You're welcome ;)
