### ISSUE TITLE
linshare single port single domain subdirs 404

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#207]
Hi, 
Want to put linshare on sigle port, single domain website in structure like this (apache):

linshare-ui-user - as root folder https://hostname
linshare-ui-admin- as subdir https://hostname/admin/
linshare-ui-upload-request- as subdir https://hostname/upload/

linshare-ui-user and linshare-ui-upload-request work just fine, but have trouble with linshare-ui-admin that not honor apache alias for  several files location, for example:

404 https://hostname/styles/AdminLTE/fonts/fontawesome-webfont.ttf?v=4.0.3
expected to be in 
https://hostname/admin/styles/AdminLTE/fonts/fontawesome-webfont.ttf?v=4.0.3

404 https://hostame/styles/linshare/fonts/sourcesanspro/sourcesanspro_normal_300.woff 
expected to be in 
https://hostame/admin/styles/linshare/fonts/sourcesanspro/sourcesanspro_normal_300.woff
 
404 https://hostame/images/68f07f39.linshare-logo-white.png
expected to be in
https://hostame/admin/images/68f07f39.linshare-logo-white.png

How can I correct this ?

**Comment by fmartin-linagora** [comment]
Hi,

Sorry you can't. Ui-admin must be deployed as root folder. Otherwise it won't work. At the time we've tried but we did not success to make it works, the issue is related to the underlying theme we are using. This is exactly why we used multiple virtual hosts for deployment in our documentation. 

For the future, we will have a new admin interface and we won't make the same error.

Hint: You can deploy ui-user as root folder and ui-upload-request on one vhost and create second vhost dedicated to ui=admin .

Regards,

**Comment by lacrimal** [comment]
Thanks, so - for now - I will use two domains and one virtual host
