### ISSUE TITLE
Quick general questions about versions, encryption, and storage.

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#213]
Hi, 
Have several questions:

1. Can I connect new Admin user interface version 5.0.0 as subdomain ?
    Remember that with previous version separate domain was needed for admin.
2. Can I use mongoDB version 4.4 instead of 4.2 ? 4.4 works just fine
3. Can mongoDB connection be encrypted ?
4. Can you say 'how much' mongoDB with gridfs storage is not recommended ? 
    I see that recommended option is jcloud with Swift however can't exactly understand how much other options are bad.
    I'm talking about installation with max 1000 users (max 200 active) and about 300GB of stored data.

**Comment by tanandy** [comment]
cc @fmartin-linagora

**Comment by fmartin-linagora** [comment]
Hello,

1. An admin per subdomain was not required in the past, so it wont be required in the new interface. But we want to delegate more stuff to this admin, so the new ui will be designed for this.
2. Yes, we are not using specific feature of Mongo 4.2, so 4.4 should works fine as far as i know.
3. I supposed it cans but we did not test it.
4. We do not recommend Gridfs to store files because LinShare is mainly designed to handle very big files, and GridFS is not the best tool for it. we are using for tests, or tiny files but we recommend to  store file on your file system or in an object storage. For example, It will be easier to backup the file system rather GridFS collection.

**Comment by lacrimal** [comment]
It's clear now for 1,2 and 3
About 4:
Using filesystem storage see that after file deletion they remain in storage.
Is there specific job to purge this files, and can I plan it more frequently ?

**Comment by fmartin-linagora** [comment]
Yes, there is a garbage collector run every night to remove useless documents.

**Comment by lacrimal** [comment]
Closing I have what was needed
