### ISSUE TITLE
Taille anormale de la base mongodb

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#222]
Ma base de données mongodb est subitement passée de 1 Go à 8 Go sans qu'il n'y ai pour autant d'ajout de fichiers correspondants. En regardant avec l'outil "MongoDB Compass", je constate que c'est la collection fs.chunks de la base de données linshare-file qui est passée à plus de 8 Go (35514 documents au sens MongoDB).
1 - Que contient la collection fs.chunks ?
2 - A quoi correspondent les fichiers "collection-N--nombre.wt (le fichier collection-0--868687193748927269.wt a une taille de 8 Go) ?
3 - Peut-on supprimer une collection et la régénérer ?
4 - Y a-t-il moyen de comparer 2 collections mongodb ?
5 - Peut-on identifier d'éventuels enregistrements "orphelins" dans MongoDB ?
En vous remerciant d'avance pour vos réponses

**Comment by tanandy** [comment]
@fmartin-linagora

**Comment by fmartin-linagora** [comment]
Bonjour,

LinShare stocke les aperçus des documents qu'i stocke, dans la base de données linshare-files. Lorsque les documents sont supprimés de LinShare, les aperçus le sont également.
Nous utilisons la technologie suivante pour stocker ces petits fichiers : https://docs.mongodb.com/manual/core/gridfs/
NB: Les fichiers sont bien stocké sur le système de fichiers ou le stockage objet.

Merci de privilégier la langue anglaise afin de favoriser le partage de connaissance pour nos lecteurs.

Fred.

**Comment by EPTBSGL** [comment]
Merci pour votre réponse,
J'ai finalement réglé le problème : il y avait eu un gros dépôt de fichiers. Lorsqu'ils ont été supprimés, la taille de la collection fs.chunks de la base de données linshare-file a bien diminué mais pas celle de la base de données. En faisant une sauvegarde puis une restauration, cela a compacté la base de données.
Si cette base est supprimée, est-elle de nouveau créée au fur et à mesure que l'on génère les aperçus ?
Thank you for your reply,
I finally solved the problem: there had been a large deposit of files. When they were deleted, the size of the fs.chunks collection in the linshare-file database did decrease but the size of the database did not. Doing a backup and then a restore compacted the database. 
If this database is deleted, is it created again as the previews are generated?

**Comment by fmartin-linagora** [comment]
Hi,

Instead of restoring a backup, you can also compact your data according to the official documentation : https://www.mongodb.com/docs/manual/reference/command/compact/

If you delete these two collections, LinShare won't find any  thumbnails so you will need to update the database to avoid HTTP 404 errors: `UPDATE document set has_thumbnail = false;`

Then you can also force LinShare to generate again all thumbnails: `UPDATE document set compute_thumbnail=true;`
A batch will run asynchronously during the night to compute all thumbnails. But be careful it could take hours according to the number of documents you have. You may want to process by range.

Fred.
