### ISSUE TITLE
[2.1.1] Default admin password

### ISSUE THREAD

**Issue by fir3wall** [linagora/linshare#39]
Hello,

After installation, we got out of the box account:  root@localhost.localdomain how to change the password for it?

Going to users screen and searching via email does not bring user across, also weird behavior is that in users screen I gave myself (linked via AD) administrator privileges - can login after this to Admin interface but cannot see half of the options (just users and audit).

Thanks
Dariusz

**Comment by fmartin-linagora** [comment]
Hi,
On Ui-Admin, at righ top of the screen you have three icons, the last one allows you to change your password.
I do not understand your second problem, do you have some screenshot to illustrate it ?

**Comment by fmartin-linagora** [comment]
Hi,
Yes, you make it right ! Admin delegation is something we should work on, nothing is missing. For now, it is not planned. I'm noticing we have an issue with the upgrade tasks (it is only available for root) that's why you get this error. I created an issue : https://github.com/linagora/linshare-ui-admin/issues/4
