### ISSUE TITLE
SSO in LinShare 2.0.0-beta

### ISSUE THREAD

**Issue by jakub-miziolek** [linagora/linshare#4]
There was possibility to integrate LinShare 1.x with CAS server. Is there such possibility with new version?

**Comment by fmartin-linagora** [comment]
Hi,
To be accurate, LinShare 0.x was supporting CAS authentication, but since 1.x, it is no longer available. We do not plan to support CAS authentication in LinShare v2. 
However, LinShare supports authentication through header injections, so you can protect the LinShare by using a Apache vhost and deal authentication with Apache mod CAS.
Fred.
